# alpine with client app

FROM alpine:latest

WORKDIR /

RUN apk add python && \
         apk add curl && \
         wget https://raw.githubusercontent.com/lavih/jenkins-python-server/master/Client.sh
        

COPY ./Client.sh /


ENTRYPOINT [ "Client.sh" ]
        
CMD /sbin/init

