# alpine with client app

FROM alpine:latest
USER root
WORKDIR /

RUN apk add python && \
         apk add curl && \
         wget https://raw.githubusercontent.com/lavih/jenkins-python-server/master/Client.sh
        

COPY ./Client.sh /

#RUN chown root:root ./Client.sh
RUN chmod 777 /Client.sh

ENTRYPOINT [ "/Client.sh" ]
        
CMD /sbin/init

