# alpine with server app

FROM alpine:latest

WORKDIR /

RUN apk add python && \
         wget https://raw.githubusercontent.com/lavih/jenkins-python-server/master/Server.py 
        # ln -sf /dev/stdout /var/log/nginx/access.log && \			
         #ln -sf /dev/stderr /var/log/nginx/error.log

COPY ./Server.py /

ENTRYPOINT [ "python", "Server.py", "&" ]
        
CMD /sbin/init


